config/routes.rb
Rails.application.routes.draw do
    resources :movies
    root :to => redirect('/movies')
    get '/movies/:id/similar_movies' => 'movies#search_similar_movies', as: :search_similar_movies

end

app/models/movie.rb
class Movie < ActiveRecord::Base
    def
        self.all_ratings ; %w[G PG PG-13 R NC-17] ; end #shortcut: array of strings
        validates :title, :presence => true
        validates :release_date, :presence => true
        validate :released_1930_or_later #uses custom validator below
        validates :rating, :inclusion => {:in => Movie.all_ratings},
            :unless => :grandfathered?

    def released_1930_or_later
        errors.add(:release_date, 'must be 1930 or later') if
            release_date && release_date < Date.parse('1 Jan 1930')
    end

    @@grandfathered_date = Date.parse('1 Nov 1968')

    def grandfathered?
        release_date && release_date < @@grandfathered_date
    end

    def self.similar_movies(movie)
        Movie.where director: movie.director
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
        if !params.key?(:ratings)
            params[:ratings] = {}
        end

        permitted = params.permit(:sort, ratings: params[:ratings].keys)
        sort = permitted[:sort] || session[:sort]

        case sort
        when 'title'
            ordering,@title_header = {:title => :asc}, 'hilite'
        when 'release_date'
            ordering,@date_header = {:release_date => :asc}, 'hilite'
        end

        @all_ratings = Movie.all_ratings
        @selected_ratings = permitted[:ratings] || session[:ratings] || {}

        if @selected_ratings == {}
            @selected_ratings = Hash[@all_ratings.map {|rating| [rating, rating]}]
        end

        if permitted[:sort] != session[:sort] or permitted[:ratings] != session[:ratings]
            session[:sort] = sort
            session[:ratings] = @selected_ratings
            redirect_to :sort => sort, :ratings => @selected_ratings and return
        end

        @movies = Movie.where(rating: @selected_ratings.keys).order(ordering)
    end

    def show
        id = params[:id]
        @movie =Movie.find(id)
    end

    def new
        @movie = Movie.new
    end

    def create
        params.require(:movie)
        permitted = params[:movie].permit(:title, :rating, :release_date, :director)
        @movie = Movie.new(permitted)
        if @movie.save
            flash[:notice] = "#{@movie.title} was successfully created."
            redirect_to movies_path
        else
            render 'new'
        end
    end

    def edit
        @movie = Movie.find params[:id]
    end

    def update
        @movie = Movie.find params[:id]
        params.require(:movie)
        permitted = params[:movie].permit(:title, :rating, :release_date, :director)
        if @movie.update_attributes(permitted)
            flash[:notice] = "#{@movie.title} was successfully updated."
            redirect_to movie_path(@movie)
        else
            render 'edit'
        end
    end

    def destroy
        @movie = Movie.find(params[:id])
        @movie.destroy
        flash[:notice] = "Movie '#{@movie.title}' deleted."
        redirect_to movies_path
    end

    def search_similar_movies
      @movie = Movie.find(params[:id])
      if @movie.director.nil? || @movie.director.empty?
        flash[:warning]= "'#{@movie.title}' has no director info"
        redirect_to movies_path
      else
        @movies = Movie.similar_movies(@movie)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title RottenPotatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    #main
      = yield

app/views/movies/edit.html.haml
-# edit.html.haml

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
%h1 All Movies
= form_tag movies_path, :method => :get, :id => 'ratings_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag "release_date_sort", true if @date_header
  Include:
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", 1, @selected_ratings.include?(rating), :id => "ratings_#{rating}"
  = submit_tag 'Refresh', :id => 'ratings_submit'
%table#movies
  %thead
    %tr
      %th{:class => @title_header}= link_to 'Movie Title', movies_path(:sort => 'title', :ratings => @selected_ratings), :id => 'title_header'
      %th Rating
      %th{:class => @date_header}= link_to 'Release Date', movies_path(:sort => 'release_date', :ratings => @selected_ratings), :id => 'release_date_header'
      %th More Info
  %tbody
  - @movies.each do |movie|
    %tr
      %td= movie.title
      %td= movie.rating
      %td= movie.release_date
      %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h2 Create New Movie

= form_tag movies_path, :method => :post do
  - unless @movie.errors.empty?
    #warning
    Errors prevented this movie from being #{controller.action_name}d:
    %ul
      - @movie.errors.full_messages.each do |error|
        %li= error
  = label :movie, :title, 'Title'
  = text_field :movie, :title

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G', 'PG', 'PG-13', 'R', 'NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/search_similar_movies.html.haml
%h1 Similar movies to #{@movie.title}

%table#similar_movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th Director
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= movie.director
        %td= link_to "More about #{movie.title}", movie_path(movie)

app/views/movies/show.html.haml
%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating

  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:
%p#description= @movie.description

= link_to 'Edit info', edit_movie_path(@movie)
= link_to 'Find Movies With Same Director', search_similar_movies_url(id: @movie.id)
= link_to 'Delete', movie_path(@movie), :method => :delete
= link_to 'Back to movie list', movies_path